name: 'Setup Python Environment'
description: 'Setup python environment and install dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.x'

runs:
  using: composite
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
    - name: Log Python Version
      shell: bash
      run: python -c "import sys; print(sys.version)"
    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install ruff pytest-playwright pytest-rerunfailures
        playwright install
