name: Pull Request Checks

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff
      - name: Lint with Ruff
        run: |
          ruff --output-format=github
        continue-on-error: false
