name: Pull Request Checks

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Setup Python Env'
        uses: ./.github/actions/setup-python
        with:
            python-version: '3.x'
      - name: 'Setup Node Env'
        uses: ./.github/actions/setup-node
        with:
            node-version: '20.x'

  lint_py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python
        with:
            python-version: '3.x'
      - name: 'Ruff Check'
        run: |
          ruff check --output-format=github

  lint_js:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
        with:
          node-version: '20.x'
      - name: 'Check JS Linting and Formatting'
        working-directory: ./st_link_analysis/frontend/
        run: |
          npm run format
          npm run lint
  
  test:
    needs: [lint_py, lint_js]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PY_VERSION: ["3.9", "3.10","3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.PY_VERSION }}
      - uses: ./.github/actions/setup-node
        with:
          node-version: '20.x'
      - run: |
          pytest
