name: Pull Request Checks

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-backend
        with:
          python-version: '3.x'
      - name: Lint with Ruff
        run: |
          ruff --output-format=github
